### ISSUE TITLE
doors

### ISSUE THREAD

**Issue by cettaur** [coolstation/coolstation#107]
multitool pulse drops door bolts but won't raise the bolts

emag welded doors are not unweldable and this causes lots of confusion

**Comment by geneva-breaker** [comment]
![image](https://user-images.githubusercontent.com/13787612/183919100-84676f23-e343-46a5-aae1-c83ece28cc14.png)
![image](https://user-images.githubusercontent.com/13787612/183919131-8d507821-f388-4ea8-84db-acaa1434f078.png)
idk seems fine, its a bit finnicky because of other things like the test lights and shit, internal cooldowns, but thats that

**Comment by geneva-breaker** [comment]
(went back and forth 12 times)
